"""
sinX Threat Hunter - Alert and Detection Rule Models
"""

from sqlalchemy import Column, Integer, String, Text, Boolean, TIMESTAMP, JSON, ForeignKey
from datetime import datetime
from ..core.database import Base


class DetectionRule(Base):
    """Detection rules for threat hunting"""
    __tablename__ = "detection_rules"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Rule identification
    name = Column(String(200), nullable=False, unique=True)
    description = Column(Text)

    # Classification
    severity = Column(String(20), index=True)  # low, medium, high, critical
    rule_type = Column(String(50), index=True)  # signature, anomaly, ioc, correlation

    # Rule definition
    rule_definition = Column(JSON, nullable=False)  # The actual rule logic

    # Configuration
    enabled = Column(Boolean, default=True, index=True)
    tags = Column(JSON)  # Array stored as JSON

    # MITRE ATT&CK mapping
    mitre_tactics = Column(JSON)  # Array stored as JSON
    mitre_techniques = Column(JSON)  # Array stored as JSON

    # Metadata
    created_at = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    updated_at = Column(TIMESTAMP(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)
    created_by = Column(String(100))

    # Statistics
    trigger_count = Column(Integer, default=0)
    false_positive_count = Column(Integer, default=0)

    def to_dict(self):
        """Convert to dictionary for API responses"""
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "severity": self.severity,
            "rule_type": self.rule_type,
            "rule_definition": self.rule_definition,
            "enabled": self.enabled,
            "tags": self.tags,
            "mitre_tactics": self.mitre_tactics,
            "mitre_techniques": self.mitre_techniques,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            "created_by": self.created_by,
            "trigger_count": self.trigger_count,
            "false_positive_count": self.false_positive_count,
        }


class Alert(Base):
    """Security alerts generated by detection rules"""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Alert identification
    title = Column(String(200), nullable=False)
    description = Column(Text)

    # Classification
    severity = Column(String(20), nullable=False, index=True)
    status = Column(String(50), default="new", index=True)  # new, investigating, resolved, false_positive

    # Relationships
    rule_id = Column(Integer, ForeignKey("detection_rules.id", ondelete="SET NULL"))
    assigned_to = Column(String(100), index=True)

    # Evidence
    related_logs = Column(JSON)  # Array of log IDs stored as JSON
    related_iocs = Column(JSON)  # Array of IOC IDs stored as JSON

    # Context
    alert_metadata = Column(JSON)  # Renamed from metadata - reserved keyword

    # MITRE ATT&CK
    mitre_tactics = Column(JSON)  # Array stored as JSON
    mitre_techniques = Column(JSON)  # Array stored as JSON

    # Temporal data
    triggered_at = Column(TIMESTAMP(timezone=True), default=datetime.utcnow, index=True)
    acknowledged_at = Column(TIMESTAMP(timezone=True))
    resolved_at = Column(TIMESTAMP(timezone=True))

    # Resolution
    resolution_notes = Column(Text)

    def to_dict(self):
        """Convert to dictionary for API responses"""
        return {
            "id": self.id,
            "title": self.title,
            "description": self.description,
            "severity": self.severity,
            "status": self.status,
            "rule_id": self.rule_id,
            "assigned_to": self.assigned_to,
            "related_logs": self.related_logs,
            "related_iocs": self.related_iocs,
            "metadata": self.alert_metadata,
            "mitre_tactics": self.mitre_tactics,
            "mitre_techniques": self.mitre_techniques,
            "triggered_at": self.triggered_at.isoformat() if self.triggered_at else None,
            "acknowledged_at": self.acknowledged_at.isoformat() if self.acknowledged_at else None,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "resolution_notes": self.resolution_notes,
        }
